name: Main Workflow

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Java JDK ${{matrix.java}}
        uses: actions/setup-java@v2.1.0
        with:
          distribution: 'adopt'
          java-version: '8'
      - name: run gradle test with Gradle Command
        uses: eskatos/gradle-command-action@v1.3.3
        with:
          arguments: clean build
      - name: report to Codecov
        uses: codecov/codecov-action@v1.5.2
