name: publish package to the Maven Central Repository when new tags create

on:
  push:
    tags:
      - '*'
jobs:
  publish:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Gradle Build Action
        uses: gradle/gradle-build-action@v2.0-beta.4
        env:
          ORG_GRADLE_PROJECT_mavenUserName: ${{ secrets.OSSRH_USERNAME }}
          ORG_GRADLE_PROJECT_mavenPassword: ${{ secrets.OSSRH_TOKEN }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_PASSPHRASE }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_PRIVATE_KEY }}
        with:
          arguments: clean publish

